---
title: "ThesisSurveyCluster"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output:
  pagedown::html_paged:
    css: www/my_css.css
    number_sections: no
knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, class.source = "watch-out", options(scipen=999), out.width = "65%", warning = FALSE, comment = "") 
source("www/init.R")
source("www/Table_Design.R")
```

```{r, echo=FALSE}
htmltools::img(
  src = knitr::image_uri(file.path("www/BSM_Logo.png")), 
  alt = 'logo', 
  style = 'position:absolute; top:0; right:5px; padding:10px; width:200px'
)
```

```{r data, echo=FALSE, include=FALSE}
data <- read_excel("Main doc survey.xlsx")
attach(data)

dani <- c( "#ffa500", "#34495E", "#69b3a2", "#ffd561", "#ee5c42", "#DAF7A6", "#C8A2C8", "#5c3170", "#990000", "#C70039", "#34495E", "#909497")

pal9 <- jcolors("pal9")
```

https://towardsdatascience.com/k-means-clustering-algorithm-applications-evaluation-methods-and-drawbacks-aa03e644b48a 


### One hot encoding

```{r}
dataf <- dummy_cols(data, select_columns = c("Machine", "BrandChange", "PurchaseLocation", "Education", "AgeCategory", "Frequency_Specialty", "Home", "Occupation", "Gender", "Subscription_Not_Likely", "Criteria_Type_Coffee", "Supermarket_Positive_ Reasons", "Supermarket_Negative_ Reasons", "Language"), remove_selected_columns = TRUE, ignore_na = TRUE)
```

```{r}
# Prepare Data
mydata <- na.omit(dataf) # listwise deletion of missing
mydata <- scale(dataf) # standardize variables
```


#### Caret package

```{r, echo=FALSE, include=FALSE}
library(caret)

dmy <- dummyVars(" ~ .", data = data[,6], fullRank = T)
dat_transformed <- data.frame(predict(dmy, newdata = data))

glimps <- glimpse(dat_transformed)
```

```{r}
# Prepare Data
mydata <- na.omit(dat_transformed) # listwise deletion of missing
mydata <- scale(dat_transformed) # standardize variables
```

### Clustering Numerical

```{r}
# Prepare Data
NumMydata <- na.omit(data[,c(2:5, 12:17, 19, 21)]) # listwise deletion of missing
Mydata <- scale(data[,c(2:5, 12:17, 19, 21)]) # standardize variables
```

```{r}
set.seed(123)

# K-Means Cluster Analysis
fit <- kmeans(na.omit(Mydata), 3, nstart = 1) #3 cluster solution
# get cluster means
aggregate(na.omit(Mydata),by=list(fit$cluster),FUN=mean)
# append cluster assignment
mydata <- data.frame(na.omit(Mydata), fit$cluster)

clusplot(mydata, fit$cluster, color=TRUE, shade=TRUE,
   labels=2, lines=0)
```

```{r}
fviz_cluster(fit, geom = "point", data = mydata, outlier.color = "black", palette = dani) +
  ggtitle("k = 3")
```

https://towardsdatascience.com/clustering-analysis-in-r-using-k-means-73eca4fb7967

```{r}
mydata <- na.omit(mydata)

distance <- get_dist(mydata)
graph <- fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))

set.seed(224)

fviz_nbclust(mydata, kmeans, method = "wss")


sil <- silhouette(fit$cluster, dist(mydata))
fviz_silhouette(sil)
```

```{r}
Results <- as.data.table(aggregate(na.omit(NumMydata), by=list(cluster=fit$cluster), mean), by = round)

Results_Round <- round(Results, 1)
my_table(Results_Round)
```


